apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notes-app
  namespace: notes
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - notes
  selector:
    matchLabels:
      app: notes-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
