apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - ingress-host.yaml
  - ingress-routes.yaml
  - deployment-image.yaml
  - deployment-securitycontext.yaml
