apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - onlyoffice-deployment.yaml
  - onlyoffice-service.yaml
  - onlyoffice-ingress.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - networkpolicy.yaml
  - pvc.yaml
