apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice
  namespace: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlyoffice
  template:
    metadata:
      labels:
        app: onlyoffice
    spec:
      containers:
        - name: onlyoffice
          image: onlyoffice/documentserver:8.1.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -eu
              JSON_BIN=/var/www/onlyoffice/documentserver/npm/json
              JSON="$JSON_BIN -I -q -f /etc/onlyoffice/documentserver/local.json"
              $JSON -e 'if(this.externalRequest===undefined)this.externalRequest={};'
              $JSON -e 'if(this.externalRequest.action===undefined)this.externalRequest.action={};'
              $JSON -e 'this.externalRequest.action.blockPrivateIP=false'
              $JSON -e 'if(this.services===undefined)this.services={};'
              $JSON -e 'if(this.services.CoAuthoring===undefined)this.services.CoAuthoring={};'
              $JSON -e 'if(this.services.CoAuthoring.server===undefined)this.services.CoAuthoring.server={};'
              $JSON -e 'this.services.CoAuthoring.server.limits_tempfile_upload=734003200'
              $JSON -e 'if(this.FileConverter===undefined)this.FileConverter={};'
              $JSON -e 'if(this.FileConverter.converter===undefined)this.FileConverter.converter={};'
              $JSON -e 'this.FileConverter.converter.maxDownloadBytes=734003200'
              $JSON -e 'if(this.FileConverter.converter.downloadTimeout===undefined)this.FileConverter.converter.downloadTimeout={};'
              $JSON -e 'this.FileConverter.converter.downloadTimeout.connectionAndInactivity="20m"'
              $JSON -e 'this.FileConverter.converter.downloadTimeout.wholeCycle="20m"'
              exec /app/ds/run-document-server.sh
          ports:
            - containerPort: 80
          env:
            - name: JWT_ENABLED
              value: "false"
            - name: ALLOW_PRIVATE_IP_ADDRESS
              value: "true"
            - name: ALLOW_META_IP_ADDRESS
              value: "true"
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 4Gi
