apiVersion: ENC[AES256_GCM,data:3Ng=,iv:JCuM4abtt+3dr4wHtqwPaLuiCI3KGcKL9MbufMWs/Ho=,tag:dqCICGti2IwjtzpYloLtKA==,type:str]
kind: ENC[AES256_GCM,data:5Lf+k9Zg,iv:NlzNGxecpHNou9jCDGS4SppEKgarNHSqogkHVpae8H8=,tag:NJVrnCHZstOeaFCauD29BQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AZZSDIf9mnNrgC4chrIl,iv:8QTgmaZ2f1Z73TQWCpViFt4bBosDYd3REVMeogFoIs8=,tag:eM7Gar7hWEFlZcyjqrhu4A==,type:str]
type: ENC[AES256_GCM,data:REHqRPcx,iv:OuYgXYYWpfjdWhDhnq4dh50dhttv9TV8CcbJ0foY7CU=,tag:sPdcjwPDQPCcOgfDWOo5qw==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ovdarL4=,iv:eiNXZbct58OjMi19IndUGXNXzYH1kxBLBZYmUfrEMC0=,tag:6isPIZaqVdt9M06gQEX4zg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fLdee+7e59hNe+VQqIjbzvot,iv:Bnqd0USGPJrrmaQ1l5YDTdSNZl6eU2FvhWkcEzObGfw=,tag:XglNIOl+tu2ZJCiynM6Pxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nlc3xraghrwnglw7qyjc2qmfdjh6ky7rhryuemcvl40u5u0qlfcsnnak9h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa1BjQmlxdWRteGgreDdo
            TTg3Vk15RkFTT3VXdHdNYXJvWEM2YVhsYmlNCll5MWlNV1hQTG9CRDQzTTRwb0JY
            RW42cCtXSThRUUU3Y0JEYndsZTREaWMKLS0tIFM0elpvOTFVeS8rVDBERURZTWJU
            MS9kcVVqTSt0L2p5eXhMZGNZTDlnODAK1VJtGsTYRNrtCPMQWGMNEboPSlfL8flS
            GsGKPKLtrQgLsf3E8egib9yksZHrpfWWzNgSaL6YVg05Y4vGffQcdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T19:29:37Z"
    mac: ENC[AES256_GCM,data:NbWTkC7gqaMmPwWaBOGdS/NrP/pRE79zYABV3f/kOWeBa120nSBsSmHaWDyhn6KvLbc2GsLNEtC3s1KjlWtZFyYwCNl75x6MBQuFX5UpoKhOu989/KpEi8RqlolfSGm4evK2sOFkbAGY3d9oa63y3jwBIFy0157lN0kFzvy7GyU=,iv:AChceBfO9CHznWt2M1PM82xju7yo2t6QNCaqHykoehI=,tag:2bMnzrFjU49ZrjJACNM/8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
