apiVersion: v1
kind: Service
metadata:
  name: notes-app
  namespace: notes
  labels:
    app: notes-app
spec:
  type: ClusterIP
  selector:
    app: notes-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
